Load relevant libraries

```{r}
library(dplyr)
library(purrr)
library(lubridate)
library(ggplot2)
library(plotly)
library(webshot2)
webshot2::webshot
```

Load in data

```{r}
econ <- read.csv("data/processed-data/final_econ_df.csv")

#Drop irrelevant column
econ <- subset(econ, select = -X)
head(econ)
```

EDA on S&P500 Closing Prices

```{r}
p_sp <- plot_ly(
  subset(econ, year(year_month) >= 1980),
  x = ~year_month,
  y = ~Closing.Price..USD.,
  type = 'scatter',
  mode = 'lines'
) %>%
  layout(
    title = "S&P 500 Monthly Closing Prices (1980–Present)",
    xaxis = list(title = "Year/Month"),
    yaxis = list(title = "Closing Price ($)")
  )

htmlwidgets::saveWidget(p_sp, "images/sp500.html")
webshot2::webshot("images/sp500.html", file = "images/sp500.png")
```

EDA on Unemployment Rates

```{r}
p_unemp <- plot_ly(
  subset(econ, year(year_month) >= 1980),
  x = ~year_month,
  y = ~Unemployment.Rate....,
  type = 'scatter',
  mode = 'lines'
) %>%
  layout(
    title = "Monthly Unemployment Rates (1980–Present)",
    xaxis = list(title = "Year/Month"),
    yaxis = list(title = "Unemployment Rate (%)")
  )

htmlwidgets::saveWidget(p_unemp, "images/unemployment.html")
webshot2::webshot("images/unemployment.html", file = "images/unemployment.png")
```


EDA on CPI

```{r}
p_cpi <- plot_ly(
  subset(econ, year(year_month) >= 1980),
  x = ~year_month,
  y = ~CPI,
  type = 'scatter',
  mode = 'lines'
) %>%
  layout(
    title = "Monthly Consumer Price Index (1980–Present)",
    xaxis = list(title = "Year/Month"),
    yaxis = list(title = "CPI (%)")
  )

htmlwidgets::saveWidget(p_cpi, "images/cpi.html")
webshot2::webshot("images/cpi.html", file = "images/cpi.png")
```


EDA on Yearly Median Household Income

```{r}
p_income <- plot_ly(
  econ %>% filter(!is.na(Median.Household.Income..USD.), year(year_month) >= 1984),
  x = ~year_month,
  y = ~Median.Household.Income..USD.,
  type = 'scatter',
  mode = 'lines'
) %>%
  layout(
    title = "Yearly Median Household Income (1984–Present)",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Median Household Income ($)")
  )

htmlwidgets::saveWidget(p_income, "images/income.html")
webshot2::webshot("images/income.html", file = "images/income.png")
```


EDA on Median Housing Price

```{r}
p_house <- plot_ly(
  econ %>% filter(!is.na(Median.Housing.Price..USD.), year(year_month) >= 1980),
  x = ~year_month,
  y = ~Median.Housing.Price..USD.,
  type = 'scatter',
  mode = 'lines'
) %>%
  layout(
    title = "Quarterly Median Housing Price (1980–Present)",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Median Housing Price ($)")
  )

htmlwidgets::saveWidget(p_house, "images/median_housing.html")
webshot2::webshot("images/median_housing.html", file = "images/median_housing.png")
```